export const peopleFormFields = {
  id: 0,
  name: '',
  cpf: '',
  foto: {},
  bairro: '',
  cep: '',
  cidade: '',
  estado: '',
  logradouro: '',
  numero: '',
  pais: '',
}
export const userFormFields = {
  cpf: '',
  dataNascimento: '',
  email: '',
  id: 0,
  nome: '',
  password: '',
  telefone: '',
  username: '',
}
export const contactFormFields = {
  email: '',
  id: 0,
  pessoa: {
    key: 0,
    label: '',
  },
  privado: true,
  tag: '',
  telefone: '',
  tipoContato: { key: '', label: '' },
  usuario: {
    cpf: '',
    dataNascimento: '',
    email: '',
    id: 0,
    nome: '',
    password: '',
    telefone: '',
    username: '',
  },
}
export const patterns = {
  B: { pattern: /[1-9]/ },
  C: { pattern: /[2-8]/ },
  D: { pattern: /0/ },
  '#': { pattern: /\d/ },
  X: { pattern: /[0-9a-zA-Z]/ },
  S: { pattern: /[a-zA-Z]/ },
  A: { pattern: /[a-zA-Z]/, transform: (v) => v.toLocaleUpperCase() },
  a: { pattern: /[a-zA-Z]/, transform: (v) => v.toLocaleLowerCase() },
  '!': { escape: true },
}
