export const peopleFormFields = {
  id: null,
  nome: '',
  cpf: '',
  foto: {},
  endereco: {
    id: null,
    bairro: '',
    cep: '',
    cidade: '',
    estado: '',
    logradouro: '',
    numero: '',
    paisOption: {
      key: '',
      label: '',
    },
    pais: '',
  },
}
export const userFormFields = {
  cpf: '',
  dataNascimento: '',
  email: '',
  id: null,
  nome: '',
  password: '',
  telefone: '',
  username: '',
  passwordConfirmation: '',
  tipoOption: {
    key: 'ROLE_USER',
    label: 'Usuário',
  },
}
export const passFormFields = {
  newPasswordConfirmation: '',
  newPassword: '',
  password: '',
  username: '',
}
export const contactFormFields = {
  email: '',
  id: null,
  pessoa: {},
  pessoaOption: {
    key: '',
    label: '',
  },
  privado: false,
  tag: '',
  telefone: '',
  tipoContato: '',
  tipoContatoOption: { key: '', label: '' },
  usuario: {
    cpf: '',
    dataNascimento: '',
    email: '',
    id: null,
    nome: '',
    password: '',
    telefone: '',
    username: '',
  },
}
export const patterns = {
  B: { pattern: /[1-9]/ },
  C: { pattern: /[2-8]/ },
  D: { pattern: /0/ },
  E: { pattern: /[12]/ },
  F: { pattern: /[09]/ },
  G: { pattern: /[0-3]/ },
  H: { pattern: /[01]/ },
  I: { pattern: /[0-2]/ },
  J: { pattern: /9/ },
  K: { pattern: /[0-8]/ },
  '#': { pattern: /\d/ },
  X: { pattern: /[0-9a-zA-Z]/ },
  S: { pattern: /[a-zA-Z]/ },
  A: { pattern: /[a-zA-Z]/, transform: (v) => v.toLocaleUpperCase() },
  a: { pattern: /[a-zA-Z]/, transform: (v) => v.toLocaleLowerCase() },
  '!': { escape: true },
}

export const optionsTiposUser = [
  { key: 'ROLE_ADMIN', label: 'Administrador' },
  { key: 'ROLE_USER', label: 'Usuário' },
]

export const libTiposUser = { ROLE_ADMIN: 'Administrador', ROLE_USER: 'Usuário' }

export const optionsTipoContato = [
  { key: 'CELULAR', label: 'Celular' },
  { key: 'EMAIL', label: 'Email' },
  { key: 'TELEFONE', label: 'Telefone' },
]

export const libTipoContato = { CELULAR: 'Celular', EMAIL: 'Email', TELEFONE: 'Telefone' }

export const optionsCountries = [
  { key: 'AD', label: 'Andorra' },
  { key: 'AE', label: 'Emirados Árabes Unidos' },
  { key: 'AF', label: 'Afeganistão' },
  { key: 'AG', label: 'Antígua e Barbuda' },
  { key: 'AI', label: 'Anguila' },
  { key: 'AL', label: 'Albânia' },
  { key: 'AM', label: 'Armênia' },
  { key: 'AO', label: 'Angola' },
  { key: 'AQ', label: 'Antártida' },
  { key: 'AR', label: 'Argentina' },
  { key: 'AS', label: 'Samoa Americana' },
  { key: 'AT', label: 'Áustria' },
  { key: 'AU', label: 'Austrália' },
  { key: 'AW', label: 'Aruba' },
  { key: 'AX', label: 'Ilhas Åland' },
  { key: 'AZ', label: 'Azerbaijão' },
  { key: 'BA', label: 'Bósnia e Herzegovina' },
  { key: 'BB', label: 'Barbados' },
  { key: 'BD', label: 'Bangladesh' },
  { key: 'BE', label: 'Bélgica' },
  { key: 'BF', label: 'Burquina Fasso' },
  { key: 'BG', label: 'Bulgária' },
  { key: 'BH', label: 'Bahrein' },
  { key: 'BI', label: 'Burundi' },
  { key: 'BJ', label: 'Benim' },
  { key: 'BL', label: 'São Bartolomeu' },
  { key: 'BM', label: 'Bermudas' },
  { key: 'BN', label: 'Brunei' },
  { key: 'BO', label: 'Bolívia' },
  { key: 'BQ', label: 'Países Baixos Caribenhos' },
  { key: 'BR', label: 'Brasil' },
  { key: 'BS', label: 'Bahamas' },
  { key: 'BT', label: 'Butão' },
  { key: 'BV', label: 'Ilha Bouvet' },
  { key: 'BW', label: 'Botswana' },
  { key: 'BY', label: 'Bielorrússia' },
  { key: 'BZ', label: 'Belize' },
  { key: 'CA', label: 'Canadá' },
  { key: 'CC', label: 'Ilhas Cocos (Keeling)' },
  { key: 'CD', label: 'República Democrática do Congo' },
  { key: 'CF', label: 'República Centro-Africana' },
  { key: 'CG', label: 'República do Congo' },
  { key: 'CH', label: 'Suíça' },
  { key: 'CI', label: 'Costa do Marfim' },
  { key: 'CK', label: 'Ilhas Cook' },
  { key: 'CL', label: 'Chile' },
  { key: 'CM', label: 'Camarões' },
  { key: 'CN', label: 'China' },
  { key: 'CO', label: 'Colômbia' },
  { key: 'CR', label: 'Costa Rica' },
  { key: 'CU', label: 'Cuba' },
  { key: 'CV', label: 'Cabo Verde Cabo Verde' },
  { key: 'CW', label: 'Curaçau' },
  { key: 'CX', label: 'Ilha do Natal' },
  { key: 'CY', label: 'Chipre' },
  { key: 'CZ', label: 'Chéquia' },
  { key: 'DE', label: 'Alemanha' },
  { key: 'DJ', label: 'Djibuti' },
  { key: 'DK', label: 'Dinamarca' },
  { key: 'DM', label: 'Dominica' },
  { key: 'DO', label: 'República Dominicana' },
  { key: 'DZ', label: 'Argélia' },
  { key: 'EC', label: 'Equador' },
  { key: 'EE', label: 'Estónia' },
  { key: 'EG', label: 'Egito' },
  { key: 'EH', label: 'Saara Ocidental' },
  { key: 'ER', label: 'Eritreia' },
  { key: 'ES', label: 'Espanha' },
  { key: 'ET', label: 'Etiópia' },
  { key: 'FI', label: 'Finlândia' },
  { key: 'FJ', label: 'Fiji' },
  { key: 'FK', label: 'Ilhas Malvinas' },
  { key: 'FM', label: 'Estados Federados da Micronésia' },
  { key: 'FO', label: 'Ilhas Feroé' },
  { key: 'FR', label: 'França' },
  { key: 'GA', label: 'Gabão' },
  { key: 'GB', label: 'Reino Unido' },
  { key: 'GD', label: 'Granada' },
  { key: 'GE', label: 'Geórgia' },
  { key: 'GF', label: 'Guiana Francesa' },
  { key: 'GG', label: 'Guernsey' },
  { key: 'GH', label: 'Gana' },
  { key: 'GI', label: 'Gibraltar' },
  { key: 'GL', label: 'Gronelândia' },
  { key: 'GM', label: 'Gâmbia' },
  { key: 'GN', label: 'Guiné' },
  { key: 'GP', label: 'Guadalupe' },
  { key: 'GQ', label: 'Guiné Equatorial' },
  { key: 'GR', label: 'Grécia' },
  { key: 'GS', label: 'Ilhas Geórgia do Sul e Sandwich do Sul' },
  { key: 'GT', label: 'Guatemala' },
  { key: 'GU', label: 'Guam' },
  { key: 'GW', label: 'Guiné-Bissau' },
  { key: 'GY', label: 'Guiana' },
  { key: 'HK', label: 'Hong Kong' },
  { key: 'HM', label: 'Ilha Heard e Ilhas McDonald' },
  { key: 'HN', label: 'Honduras' },
  { key: 'HR', label: 'Croácia' },
  { key: 'HT', label: 'Haiti' },
  { key: 'HU', label: 'Hungria' },
  { key: 'ID', label: 'Indonésia' },
  { key: 'IE', label: 'Irlanda' },
  { key: 'IL', label: 'Israel' },
  { key: 'IM', label: 'Ilha de Man' },
  { key: 'IN', label: 'Índia' },
  { key: 'IO', label: 'Território Britânico do Oceano Índico' },
  { key: 'IQ', label: 'Iraque' },
  { key: 'IR', label: 'Irã Irão' },
  { key: 'IS', label: 'Islândia' },
  { key: 'IT', label: 'Itália' },
  { key: 'JE', label: 'Jersey' },
  { key: 'JM', label: 'Jamaica' },
  { key: 'JO', label: 'Jordânia' },
  { key: 'JP', label: 'Japão' },
  { key: 'KE', label: 'Quênia' },
  { key: 'KG', label: 'Quirguistão' },
  { key: 'KH', label: 'Camboja Camboja' },
  { key: 'KI', label: 'Kiribati' },
  { key: 'KM', label: 'Comores' },
  { key: 'KN', label: 'São Cristóvão e Neves' },
  { key: 'KP', label: 'Coreia do Norte' },
  { key: 'KR', label: 'Coreia do Sul Coreia do Sul' },
  { key: 'KW', label: 'Kuwait' },
  { key: 'KY', label: 'Ilhas Caimã' },
  { key: 'KZ', label: 'Cazaquistão' },
  { key: 'LA', label: 'Laos Laos' },
  { key: 'LB', label: 'Líbano' },
  { key: 'LC', label: 'Santa Lúcia' },
  { key: 'LI', label: 'Liechtenstein' },
  { key: 'LK', label: 'Sri Lanka' },
  { key: 'LR', label: 'Libéria' },
  { key: 'LS', label: 'Lesoto' },
  { key: 'LT', label: 'Lituânia' },
  { key: 'LU', label: 'Luxemburgo' },
  { key: 'LV', label: 'Letônia' },
  { key: 'LY', label: 'Líbia' },
  { key: 'MA', label: 'Marrocos' },
  { key: 'MC', label: 'Mónaco' },
  { key: 'MD', label: 'Moldávia' },
  { key: 'ME', label: 'Montenegro' },
  { key: 'MF', label: 'São Martinho' },
  { key: 'MG', label: 'Madagáscar' },
  { key: 'MH', label: 'Ilhas Marshall' },
  { key: 'MK', label: 'Macedónia do Norte Macedônia do Norte' },
  { key: 'ML', label: 'Mali' },
  { key: 'MM', label: 'Myanmar Myanmar' },
  { key: 'MN', label: 'Mongólia Mongólia' },
  { key: 'MO', label: 'Macau' },
  { key: 'MP', label: 'Marianas Setentrionais' },
  { key: 'MQ', label: 'Martinica' },
  { key: 'MR', label: 'Mauritânia' },
  { key: 'MS', label: 'Monserrate' },
  { key: 'MT', label: 'Malta' },
  { key: 'MU', label: 'Ilhas Maurícias' },
  { key: 'MV', label: 'Maldivas' },
  { key: 'MW', label: 'Malawi' },
  { key: 'MX', label: 'México' },
  { key: 'MY', label: 'Malásia' },
  { key: 'MZ', label: 'Moçambique' },
  { key: 'NA', label: 'Namíbia' },
  { key: 'NC', label: 'Nova Caledônia' },
  { key: 'NE', label: 'Níger' },
  { key: 'NF', label: 'Ilha Norfolk' },
  { key: 'NG', label: 'Nigéria' },
  { key: 'NI', label: 'Nicarágua' },
  { key: 'NL', label: 'Países Baixos' },
  { key: 'NO', label: 'Noruega' },
  { key: 'NP', label: 'Nepal' },
  { key: 'NR', label: 'Nauru' },
  { key: 'NU', label: 'Niue' },
  { key: 'NZ', label: 'Nova Zelândia' },
  { key: 'OM', label: 'Omã Omã' },
  { key: 'PA', label: 'Panamá' },
  { key: 'PE', label: 'Peru' },
  { key: 'PF', label: 'Polinésia Francesa' },
  { key: 'PG', label: 'Papua-Nova Guiné' },
  { key: 'PH', label: 'Filipinas' },
  { key: 'PK', label: 'Paquistão' },
  { key: 'PL', label: 'Polónia' },
  { key: 'PM', label: 'São Pedro e Miquelão' },
  { key: 'PN', label: 'Pitcairn' },
  { key: 'PR', label: 'Porto Rico' },
  { key: 'PS', label: 'Palestina' },
  { key: 'PT', label: 'Portugal Portugal' },
  { key: 'PW', label: 'Palau' },
  { key: 'PY', label: 'Paraguai' },
  { key: 'QA', label: 'Catar' },
  { key: 'RE', label: 'Reunião' },
  { key: 'RO', label: 'Roménia' },
  { key: 'RS', label: 'Sérvia' },
  { key: 'RU', label: 'Rússia' },
  { key: 'RW', label: 'Ruanda' },
  { key: 'SA', label: 'Arábia Saudita' },
  { key: 'SB', label: 'Ilhas Salomão' },
  { key: 'SC', label: 'Seicheles' },
  { key: 'SD', label: 'Sudão' },
  { key: 'SE', label: 'Suécia' },
  { key: 'SG', label: 'Singapura Singapura' },
  { key: 'SH', label: 'Santa Helena, Ascensão e Tristão da Cunha' },
  { key: 'SI', label: 'Eslovênia' },
  { key: 'SJ', label: 'Svalbard e Jan Mayen' },
  { key: 'SK', label: 'Eslováquia' },
  { key: 'SL', label: 'Serra Leoa' },
  { key: 'SM', label: 'San Marino' },
  { key: 'SN', label: 'Senegal' },
  { key: 'SO', label: 'Somália' },
  { key: 'SR', label: 'Suriname' },
  { key: 'SS', label: 'Sudão do Sul' },
  { key: 'ST', label: 'São Tomé e Príncipe' },
  { key: 'SV', label: 'El Salvador' },
  { key: 'SX', label: 'São Martinho' },
  { key: 'SY', label: 'Síria Síria' },
  { key: 'SZ', label: 'Essuatíni' },
  { key: 'TC', label: 'Turcas e Caicos' },
  { key: 'TD', label: 'Chade' },
  { key: 'TF', label: 'Terras Austrais e Antárticas Francesas' },
  { key: 'TG', label: 'Togo' },
  { key: 'TH', label: 'Tailândia' },
  { key: 'TJ', label: 'Tajiquistão' },
  { key: 'TK', label: 'Toquelau' },
  { key: 'TL', label: 'Timor-Leste' },
  { key: 'TM', label: 'Turquemenistão' },
  { key: 'TN', label: 'Tunísia' },
  { key: 'TO', label: 'Tonga' },
  { key: 'TR', label: 'Turquia' },
  { key: 'TT', label: 'Trinidad e Tobago' },
  { key: 'TV', label: 'Tuvalu' },
  { key: 'TW', label: 'Taiwan' },
  { key: 'TZ', label: 'Tanzânia' },
  { key: 'UA', label: 'Ucrânia' },
  { key: 'UG', label: 'Uganda' },
  { key: 'UM', label: 'Ilhas Menores Distantes dos Estados Unidos' },
  { key: 'US', label: 'Estados Unidos' },
  { key: 'UY', label: 'Uruguai' },
  { key: 'UZ', label: 'Uzbequistão' },
  { key: 'VA', label: 'Vaticano' },
  { key: 'VC', label: 'São Vicente e Granadinas' },
  { key: 'VE', label: 'Venezuela' },
  { key: 'VG', label: 'Ilhas Virgens Britânicas' },
  { key: 'VI', label: 'Ilhas Virgens Americanas' },
  { key: 'VN', label: 'Vietname' },
  { key: 'VU', label: 'Vanuatu' },
  { key: 'WF', label: 'Wallis e Futuna' },
  { key: 'WS', label: 'Samoa' },
  { key: 'YE', label: 'Iêmen' },
  { key: 'YT', label: 'Mayotte' },
  { key: 'ZA', label: 'África do Sul' },
  { key: 'ZM', label: 'Zâmbia' },
  { key: 'ZW', label: 'Zimbabwe' },
]
