export const listContact = [
  {
    id: 12,
    email: 'email@email.com',
    privado: true,
    tag: 'Um contato legal',
    telefone: '(51) 8 8888-8888',
    tipoContato: 'TELEFONE',
    pessoa: {
      cpf: '000.000.000-00',
      id: 1,
      nome: 'string1',
      endereco: {
        bairro: 'string',
        cep: '00000-000',
        cidade: 'string',
        estado: 'string',
        id: 15,
        logradouro: 'string',
        numero: 123,
        pais: 'BR',
      },
      foto: {
        id: '123',
        name: 'string',
        type: 'png',
      },
    },
    usuario: {
      cpf: '111.111.111-11',
      dataNascimento: '2025.11.11',
      email: 'usuario@email.com',
      id: 16,
      nome: 'usuario1',
      password: 'senha',
      telefone: '(51) 9 9999-9999',
      username: 'username1',
    },
  },
  {
    id: 22,
    email: 'email@email.com',
    privado: false,
    tag: 'Um contato legal',
    telefone: '',
    tipoContato: 'EMAIL',
    pessoa: {
      cpf: '000.000.000-00',
      id: 2,
      nome: 'string2',
      endereco: {
        bairro: 'string',
        cep: '00000-000',
        cidade: 'string',
        estado: 'string',
        id: 25,
        logradouro: 'string',
        numero: 123,
        pais: 'BR',
      },
      foto: {
        id: '123',
        name: 'string',
        type: 'png',
      },
    },
    usuario: {
      cpf: '000.000.000-00',
      dataNascimento: '2025.11.11',
      email: 'usuario@email.com',
      id: 26,
      nome: 'usuario1',
      password: 'senha',
      telefone: '(51) 9 9999-9999',
      username: 'username1',
    },
  },
]

export const listPeople = [
  {
    cpf: '000.000.000-00',
    id: 1,
    nome: 'string1',
    endereco: {
      bairro: 'string',
      cep: '00000-000',
      cidade: 'string',
      estado: 'string',
      id: 15,
      logradouro: 'string',
      numero: 123,
      pais: 'BR',
    },
    foto: {
      id: '123',
      name: 'string',
      type: 'png',
    },
  },
  {
    cpf: '000.000.000-00',
    id: 2,
    nome: 'string2',
    endereco: {
      bairro: 'string',
      cep: '00000-000',
      cidade: 'string',
      estado: 'string',
      id: 25,
      logradouro: 'string',
      numero: 123,
      pais: 'BR',
    },
    foto: {
      id: '123',
      name: 'string',
      type: 'png',
    },
  },
]
